/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface SocketIo {
    'channelName': string;
    'listenOn': string;
  }
  interface SocketIoAttributes extends StencilHTMLAttributes {
    'channelName'?: string;
    'listenOn'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'SocketIo': Components.SocketIo;
  }

  interface StencilIntrinsicElements {
    'socket-io': Components.SocketIoAttributes;
  }


  interface HTMLSocketIoElement extends Components.SocketIo, HTMLStencilElement {}
  var HTMLSocketIoElement: {
    prototype: HTMLSocketIoElement;
    new (): HTMLSocketIoElement;
  };

  interface HTMLElementTagNameMap {
    'socket-io': HTMLSocketIoElement
  }

  interface ElementTagNameMap {
    'socket-io': HTMLSocketIoElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
